In [23]:
import pandas as pd

metadata = pd.read_csv('data/metadata.csv', index_col=0)
metadata

,Age,Gender,Smoking_History,Tumor_Size_mm,Histological_Grade,Lymph_Node_Involvement,Metastasis,Treatment,Response_to_Treatment,Follow_up_Duration_months,Survival_Status,Family_History_of_Cancer,Ethnicity
Patient_ID,,,,,,,,,,,,,
BC.1,70,Male,No,31,Low,No,No,Surgery,Complete Remission,25,Survived,No,Caucasian
BC.2,54,Male,Yes,34,Intermediate,No,No,Combination,Complete Remission,40,Survived,Yes,Hispanic
BC.3,53,Male,Yes,39,Intermediate,Yes,No,Chemotherapy,Complete Remission,19,Survived,No,African-American
BC.4,42,Male,No,31,Low,No,No,Radiation,Complete Remission,42,Survived,Yes,Other
BC.5,81,Male,Yes,34,Intermediate,Yes,No,Surgery,Complete Remission,60,Survived,No,Caucasian
...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC.136,50,Male,Yes,127,High,No,No,Radiation,Progressive Disease,56,Deceased,No,Caucasian
BC.137,75,Female,Yes,104,High,No,Yes,Surgery,Partial Remission,18,Deceased,No,Caucasian
BC.138,83,Female,No,143,Low,Yes,No,Radiation,Progressive Disease,55,Deceased,No,Asian
BC.139,85,Male,Yes,114,High,No,Yes,Combination,Progressive Disease,20,Deceased,No,Caucasian
BC.140,58,Male,Yes,126,High,No,No,Radiation,Progressive Disease,18,Deceased,Yes,African-American

In [24]:
protein_data = pd.read_csv('data/proteomics.txt', header=0, index_col=0, sep='\t').T
protein_data.index_name = 'Patient_ID'
protein_data

Protein_ID,A1BG,A2M,AAMDC,AARS1,AASDHPPT,AASS,ABAT,ABCC4,ABCE1,ABCF1,...,YWHAE,YWHAG,YWHAH,YWHAQ,YWHAZ,ZADH2,ZFHX3,ZNF185,ZNF207,ZYX
BC.1,1.047640e+09,1.304314e+10,35395800.00,77138600.00,1322772.000,2.149774e+07,1.615196e+07,2294820.000,1.101012e+07,24670800.00,...,2.717220e+09,7.508160e+08,577654000.0,1.149346e+09,7.624540e+09,9.264420e+06,4.984337e+05,1.496858e+07,1.708168e+07,102436400.0
BC.2,1.113700e+09,6.184000e+09,58690000.00,96508000.00,9252077.742,3.165600e+06,8.644212e+06,1917313.735,1.235980e+07,8326600.00,...,1.876420e+09,8.162600e+08,480040000.0,1.047000e+09,6.705200e+09,2.910213e+06,3.593441e+05,4.789986e+05,1.293843e+06,292820000.0
BC.3,1.055760e+09,6.564800e+09,9091800.00,46406000.00,3913600.000,4.620000e+06,4.325549e+06,3463000.000,2.843400e+06,7310400.00,...,1.758920e+09,1.137120e+09,697180000.0,1.359340e+09,8.877000e+09,1.543817e+06,6.227843e+05,3.823402e+05,3.410526e+06,168724000.0
BC.4,1.104000e+09,4.329400e+09,41908000.00,17550000.00,1687937.466,5.226863e+06,7.219093e+06,3200134.601,1.423474e+06,6473600.00,...,1.184080e+09,6.620400e+08,473080000.0,7.363200e+08,3.372000e+09,2.494988e+06,3.323255e+05,4.357254e+05,1.235035e+07,651260000.0
BC.5,1.158380e+09,9.797400e+09,39804000.00,56650000.00,5560375.423,9.672200e+06,8.832000e+06,5298370.284,7.971200e+06,7818800.00,...,2.570000e+09,7.799800e+08,419820000.0,1.485820e+09,7.733800e+09,5.560051e+05,8.482400e+07,4.351219e+05,1.137900e+07,213560000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC.136,1.060922e+09,9.254695e+09,39653134.70,47078585.81,4646577.381,1.205269e+07,1.250407e+07,5985181.092,6.624340e+06,13245682.25,...,1.527129e+09,5.248372e+08,291284890.4,6.644021e+08,4.191205e+09,3.352999e+06,3.594246e+07,7.468710e+06,9.313667e+06,312958883.9
BC.137,9.211745e+08,8.989629e+09,42055883.58,44975411.69,4703299.970,1.210398e+07,1.246855e+07,6126325.965,6.627933e+06,13307683.82,...,1.546514e+09,5.514091e+08,290966152.7,6.577622e+08,4.196481e+09,3.786910e+06,4.663867e+07,7.140596e+06,1.158332e+07,262692872.1
BC.138,9.034938e+08,9.166813e+09,39200243.47,47029104.10,5754406.976,8.733812e+06,9.521226e+06,5979016.627,6.743236e+06,12100032.37,...,1.506076e+09,5.192202e+08,276745659.8,6.582320e+08,4.201648e+09,2.621293e+06,3.853201e+07,7.737410e+06,9.407731e+06,263100145.2
BC.139,9.445144e+08,8.404558e+09,39613364.26,44595944.29,4575239.221,8.581587e+06,9.550733e+06,8766175.378,6.685868e+06,12645010.21,...,1.643239e+09,5.201992e+08,276991147.1,6.572683e+08,4.189549e+09,2.982408e+06,3.607037e+07,8.751533e+06,1.094825e+07,266445555.3
BC.140,9.872748e+08,8.388665e+09,39404850.11,47672052.73,5332221.386,8.388704e+06,9.637006e+06,6013270.608,6.673324e+06,12414329.49,...,1.639191e+09,5.254229e+08,278206582.3,6.603025e+08,4.191163e+09,2.702994e+06,3.605619e+07,8.342621e+06,9.413094e+06,264261404.9

In [28]:
combined_df = metadata.merge(protein_data, 
               left_index=True,
               right_index=True,
               how='inner')
combined_df

,Age,Gender,Smoking_History,Tumor_Size_mm,Histological_Grade,Lymph_Node_Involvement,Metastasis,Treatment,Response_to_Treatment,Follow_up_Duration_months,...,YWHAE,YWHAG,YWHAH,YWHAQ,YWHAZ,ZADH2,ZFHX3,ZNF185,ZNF207,ZYX
BC.1,70,Male,No,31,Low,No,No,Surgery,Complete Remission,25,...,2.717220e+09,7.508160e+08,577654000.0,1.149346e+09,7.624540e+09,9.264420e+06,4.984337e+05,1.496858e+07,1.708168e+07,102436400.0
BC.2,54,Male,Yes,34,Intermediate,No,No,Combination,Complete Remission,40,...,1.876420e+09,8.162600e+08,480040000.0,1.047000e+09,6.705200e+09,2.910213e+06,3.593441e+05,4.789986e+05,1.293843e+06,292820000.0
BC.3,53,Male,Yes,39,Intermediate,Yes,No,Chemotherapy,Complete Remission,19,...,1.758920e+09,1.137120e+09,697180000.0,1.359340e+09,8.877000e+09,1.543817e+06,6.227843e+05,3.823402e+05,3.410526e+06,168724000.0
BC.4,42,Male,No,31,Low,No,No,Radiation,Complete Remission,42,...,1.184080e+09,6.620400e+08,473080000.0,7.363200e+08,3.372000e+09,2.494988e+06,3.323255e+05,4.357254e+05,1.235035e+07,651260000.0
BC.5,81,Male,Yes,34,Intermediate,Yes,No,Surgery,Complete Remission,60,...,2.570000e+09,7.799800e+08,419820000.0,1.485820e+09,7.733800e+09,5.560051e+05,8.482400e+07,4.351219e+05,1.137900e+07,213560000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC.136,50,Male,Yes,127,High,No,No,Radiation,Progressive Disease,56,...,1.527129e+09,5.248372e+08,291284890.4,6.644021e+08,4.191205e+09,3.352999e+06,3.594246e+07,7.468710e+06,9.313667e+06,312958883.9
BC.137,75,Female,Yes,104,High,No,Yes,Surgery,Partial Remission,18,...,1.546514e+09,5.514091e+08,290966152.7,6.577622e+08,4.196481e+09,3.786910e+06,4.663867e+07,7.140596e+06,1.158332e+07,262692872.1
BC.138,83,Female,No,143,Low,Yes,No,Radiation,Progressive Disease,55,...,1.506076e+09,5.192202e+08,276745659.8,6.582320e+08,4.201648e+09,2.621293e+06,3.853201e+07,7.737410e+06,9.407731e+06,263100145.2
BC.139,85,Male,Yes,114,High,No,Yes,Combination,Progressive Disease,20,...,1.643239e+09,5.201992e+08,276991147.1,6.572683e+08,4.189549e+09,2.982408e+06,3.607037e+07,8.751533e+06,1.094825e+07,266445555.3
BC.140,58,Male,Yes,126,High,No,No,Radiation,Progressive Disease,18,...,1.639191e+09,5.254229e+08,278206582.3,6.603025e+08,4.191163e+09,2.702994e+06,3.605619e+07,8.342621e+06,9.413094e+06,264261404.9